name: Update LeetCode Streak Badge

on:
  schedule:
    - cron: '0 0 * * *'       # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and update streak
        run: |
          python .github/scripts/update_streak.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update LeetCode streak" || echo "No changes to commit"
          git push
